.TH BIBLEDIT-BIBLETIME 1 "January 31 2009" "Version 3.6"
.SH NAME
.B bibledit-bibletime \- internal command for bibledit, a Bible editor
.SH DESCRIPTION
Bibledit is a Bible editor.
It is started by typing "bibledit" on
the commandline. 
Binary "bibledit-bibletime" is used by Bibledit internally.
For more information see the 
online help of the graphical user interface.
.PP
.SH LICENSE
This program is distributed under the GNU General Public License, as noted in
each source file.
