#!/bin/bash

rm ~/Desktop/libgit2.a
rm -rf ~/Desktop/git2
cd ..
cd libgit2*
rm -rf build
mkdir build
cd build
cmake .. -DBUILD_SHARED_LIBS=OFF -DBUILD_CLAR=OFF -DTHREADSAFE=ON
cmake --build .
cp -r ../include ~/Desktop/git2
cp libgit2.a ~/Desktop
cd ..
rm -rf build
echo It everything went well, then libgit2 has been built for OS X.
echo The output was copied to the Desktop.
