.TH BIBLEDIT-GTK 1 "April 10 2012" "Version 4.6"
.SH NAME
.B bibledit-gtk \- a Bible editor
.SH DESCRIPTION
Bibledit-Gtk is a Bible editor.
It is started by typing "bibledit-gtk" on
the commandline. For more information see the 
online help of the graphical user interface.
.PP
.SH LICENSE
This program is distributed under the GNU General Public License, as noted in
each source file.
