/* confdefs.h */
#define PACKAGE_NAME "bibledit"
#define PACKAGE_TARNAME "bibledit"
#define PACKAGE_VERSION "1.0.163"
#define PACKAGE_STRING "bibledit 1.0.163"
#define PACKAGE_BUGREPORT "http://bibledit.org"
#define PACKAGE_URL ""
#define PACKAGE "bibledit"
#define VERSION "1.0.163"
#define PACKAGE "bibledit"
#define VERSION "1.0.163"
