#!/bin/bash


# Run this script from the directory where it is located: ./native.
# Prerequisites:
# Android SDK for Mac OS X.


# Export environment variables to find the Android SDK and NDK tools.
export ANDROID_HOME=~/scr/android-sdk-macosx
export PATH=$PATH:~/scr/android-sdk-macosx/platform-tools:~/scr/android-sdk-macosx/tools:~/scr/android-ndk-r10e


# Refresh the bibledit-web source code in the assets.
rsync -a --exclude '*.o' --delete ../lib/* jni
pushd jni
./configure --enable-client --with-parallel-tasks=3 --enable-bare-browser --enable-tinyjournal --disable-icu
rm -f bibledit
rm -r autom4te.cache
rm dev
rm -f *.a
rm reconfigure
rm -f server
rm -f unittest
rm valgrind
rm -r xcode
rm -r executable
rm aclocal.m4
rm AUTHORS
rm ChangeLog
rm compile
rm config.guess
rm config.h.in
rm config.log
rm config.status
rm config.sub
rm configure
rm configure.ac
rm COPYING
rm depcomp
rm DEVELOP
rm INSTALL
rm install-sh
rm Makefile
rm Makefile.in
rm missing
rm NEWS
rm README
rm stamp-h1
rm -rf sources/hebrewlexicon
rm -rf sources/morphgnt
rm -rf sources/morphhb
rm -rf sources/sblgnt
popd


# Remove some data so that the .apk does not exceed 50 Mbytes - the limit Google Play puts on it.
echo "delete from data;" | sqlite3 jni/databases/etcb4.sqlite
echo "delete from word;" | sqlite3 jni/databases/etcb4.sqlite
echo "delete from vocalized_lexeme;" | sqlite3 jni/databases/etcb4.sqlite
echo "delete from consonantal_lexeme;" | sqlite3 jni/databases/etcb4.sqlite
echo "delete from gloss;" | sqlite3 jni/databases/etcb4.sqlite
echo "vacuum;" | sqlite3 jni/databases/etcb4.sqlite

echo "delete from morphhb;" | sqlite3 jni/databases/morphhb.sqlite
echo "delete from parsing;" | sqlite3 jni/databases/morphhb.sqlite
echo "delete from word;" | sqlite3 jni/databases/morphhb.sqlite
echo "vacuum;" | sqlite3 jni/databases/morphhb.sqlite


# Android does not provide 'stoi' in C++.
sed -i.bak '/HAVE_STOI/d' jni/config.h
rm jni/config.h.bak


# The following command saves all source files from Makefile.am to file.
# It uses several steps to obtain the result:
# * Obtain source files between the correct patterns.
# * Remove first line.
# * Remove last line.
# * Remove tabs.
# * Remove new lines.
# * Remove backslashes.
sed -n "/libbibledit_a_SOURCES/,/bin_PROGRAMS/p" jni/Makefile.am | tail -n +2 | sed '$d' | strings | tr -d '\n' | sed 's/\\//g' > jni/sources.txt


# Create Android.mk Makefile from Android.mk.am.
sed "s|SOURCEFILES|$(cat jni/sources.txt)|" jni/Android.am > jni/Android.mk
rm jni/sources.txt


# Build native code.
# https://developer.android.com/tools/sdk/ndk/index.html
ndk-build clean
ndk-build NDK_DEBUG=1
