.TH BIBLEDIT-BIBLETIME 1 "December 28 2009" "Version 4.1"
.SH NAME
.B bibledit-bibletime \- Bibledit BibleTime helper
.SH DESCRIPTION
Bibledit-BibleTime interfaces between Bibledit and BibleTime.
It is started by typing "bibledit-bibletime" on the commandline. 
For more information see the graphical user interface.
.PP
.SH LICENSE
This program is distributed under the GNU General Public License, as noted in
each source file.
