USE `BIBLEDITDATABASE`;

CREATE TABLE IF NOT EXISTS sessions (
  id int,
  timestamp int,
  identifier varchar(256),
  value varchar(256)
) engine = MyISAM;

DROP PROCEDURE IF EXISTS upgrades;
DELIMITER ;;
CREATE PROCEDURE upgrades ()
BEGIN
  DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
  DECLARE CONTINUE HANDLER FOR 1061 BEGIN END;
  DECLARE CONTINUE HANDLER FOR 1091 BEGIN END;
  ALTER TABLE sessions ENGINE = MYISAM;
END;;
CALL upgrades();;
DROP PROCEDURE upgrades;
