.TH BIBLEDIT-LINUX 1 "October 28 2014" "Version 1.0"
.SH NAME
.B bibledit-linux \- Bibledit for Linux
.SH DESCRIPTION
Bibledit-Linux is the Linux port of Bibledit.
It is started by typing "bibledit-linux" on the commandline. 
For more information see the graphical user interface.
.PP
.SH LICENSE
This program is distributed under the GNU General Public License, as noted in
each source file.
