.TH BIBLEDIT 1 "May 13 2015" "Version 1.0"
.SH NAME
.B bibledit \- Bibledit for Linux
.SH DESCRIPTION
Bibledit is a Bible editor.
It is started by typing "bibledit" on the commandline.
For more information see the graphical user interface.
.PP
.SH LICENSE
This program is distributed under the GNU General Public License, as noted in
each source file.
