.TH BIBLEDIT-XIPHOS 1 "December 28 2009" "Version 4.1"
.SH NAME
.B bibledit-xiphos \- Bibledit Xiphos helper
.SH DESCRIPTION
Bibledit-Xiphos interfaces between Bibledit and Xiphos.
It is started by typing "bibledit-xiphos" on the commandline. 
For more information see the graphical user interface.
.PP
.SH LICENSE
This program is distributed under the GNU General Public License, as noted in
each source file.
